apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.labels }}
  labels:
    app: {{ .Values.app.labels }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.labels }}
    spec:
      containers:
      - name: {{ .Values.app.labels }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /keyuna/api/hello
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        env:
        - name: YOUR_NAME
          valueFrom:
            configMapKeyRef: 
              name: {{ .Values.app.name }}
              key: YOUR_NAME  