steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  dir:  "/spring-boot-app"
  args: ["build", "-t", "gcr.io/sandbox-io-289003/image:tag", "."]
#   # push container image
# - name: "gcr.io/cloud-builders/docker"
#   args: ["push", "gcr.io/sandbox-io-289003/image:tag"]
#   # deploy container image to GKE
# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=kubernetes-resource-file
#   - --image=gcr.io/project-id/image:tag
#   - --location=location
#   - --cluster=cluster