pipeline {
    agent {
        docker { image 'spring-boot-docker' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'spring-boot-docker'
            }
        }
    }
}