apiVersion: v1
kind: Service
metadata:
  name: key-lb-service
spec:
  type: LoadBalancer
  selector:
    app: products
    department: sales
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080